//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationContract
    {
        public int Code { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> DateOfConclusionContract { get; set; }
        public string TypeContract { get; set; }
        public string ReasonTerminationContract { get; set; }
        public string PersonalNumber { get; set; }
        public string Services { get; set; }
        public Nullable<System.DateTime> DateTerminationContract { get; set; }
        public string SerialNumberEquipment { get; set; }
    
        public virtual InformationSubscriber InformationSubscriber { get; set; }
    }
}
