//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informationlocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informationlocation()
        {
            this.InstalledEquipment = new HashSet<InstalledEquipment>();
        }
    
        public int Code { get; set; }
        public string InstallationAddres { get; set; }
        public string ConnectionPoint { get; set; }
        public string Installationlocation { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public string GatewayPhoneNumber { get; set; }
        public string PhoneList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipment> InstalledEquipment { get; set; }
    }
}
